"""Archivist agent: living context (CODEBASE.md), onboarding brief, semantic index, cartography trace.

Phase 4: Produces artifacts for AI coding agents and downstream tooling. Every action logged to trace.
"""

import json
import logging
from pathlib import Path
from typing import Any

import networkx as nx

from src.graph.knowledge_graph import KnowledgeGraph

logger = logging.getLogger(__name__)


def _safe_get(d: dict, key: str, default: Any = "") -> Any:
    return d.get(key, default) if isinstance(d, dict) else default


def generate_CODEBASE_md(
    module_graph: nx.DiGraph,
    lineage_graph: nx.DiGraph,
    survey_analytics: dict,
    day_one_answers: dict,
    repo_name: str = "codebase",
) -> str:
    """
    Generate the living context file for injection into AI coding agents.
    Sections: Architecture Overview, Critical Path, Data Sources & Sinks, Known Debt,
    High-Velocity Files, Module Purpose Index.
    """
    lines: list[str] = [
        f"# {repo_name} — Living Context",
        "",
        "Auto-generated by the Brownfield Cartographer. Inject this file into an AI coding agent for instant architectural awareness.",
        "",
        "---",
        "",
        "## Architecture Overview",
        "",
    ]

    n_mod = module_graph.number_of_nodes()
    n_edge = module_graph.number_of_edges()
    n_lineage = lineage_graph.number_of_nodes()
    lines.append(f"This codebase has **{n_mod}** modules (files) with **{n_edge}** import edges and **{n_lineage}** nodes in the data lineage graph. ")
    lines.append("Modules are analyzed for imports, public API, complexity, and purpose; lineage tracks data flow from sources to sinks.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Critical Path (Top 5 Modules by PageRank)")
    lines.append("")
    pagerank_list = sorted(
        [(n, _safe_get(module_graph.nodes[n], "pagerank") or 0) for n in module_graph.nodes()],
        key=lambda x: -x[1],
    )[:5]
    for path, score in pagerank_list:
        purpose = _safe_get(module_graph.nodes[path], "purpose_statement")
        purpose_line = f" — {purpose[:120]}..." if purpose and len(purpose) > 120 else (f" — {purpose}" if purpose else "")
        lines.append(f"- **{path}** (PageRank: {score:.4f}){purpose_line}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Data Sources & Sinks")
    lines.append("")
    sources = [n for n in lineage_graph.nodes() if lineage_graph.in_degree(n) == 0]
    sinks = [n for n in lineage_graph.nodes() if lineage_graph.out_degree(n) == 0]
    lines.append("**Sources (in-degree 0):** " + (", ".join(sources[:25]) if sources else "—"))
    lines.append("")
    lines.append("**Sinks (out-degree 0):** " + (", ".join(sinks[:25]) if sinks else "—"))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Known Debt")
    lines.append("")
    cycles = survey_analytics.get("cycles") or []
    if cycles:
        lines.append("- **Circular dependencies:** " + str(len(cycles)) + " cycle(s) detected.")
        for i, c in enumerate(cycles[:5]):
            lines.append(f"  - Cycle {i + 1}: {', '.join(list(c)[:8])}")
    else:
        lines.append("- **Circular dependencies:** None detected.")
    drift_nodes = [n for n in module_graph.nodes() if module_graph.nodes[n].get("documentation_drift")]
    if drift_nodes:
        lines.append("- **Documentation drift (docstring contradicts code):** " + ", ".join(drift_nodes[:15]))
    else:
        lines.append("- **Documentation drift:** None flagged.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## High-Velocity Files (Recent Change Hotspots)")
    lines.append("")
    high_vel = survey_analytics.get("high_velocity_files") or []
    if high_vel:
        for p in high_vel[:20]:
            lines.append(f"- {p}")
    else:
        lines.append("(No velocity data or no high-velocity files.)")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Module Purpose Index")
    lines.append("")
    for n in list(module_graph.nodes())[:80]:
        d = module_graph.nodes[n]
        purpose = _safe_get(d, "purpose_statement")
        domain = _safe_get(d, "domain_cluster")
        if purpose or domain:
            lines.append(f"- **{n}**")
            if domain:
                lines.append(f"  - Domain: {domain}")
            if purpose:
                lines.append(f"  - Purpose: {purpose[:200]}" + ("..." if len(purpose) > 200 else ""))
            lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Day-One Brief (Summary)")
    lines.append("")
    for i, q in enumerate((day_one_answers.get("questions") or [])[:5], 1):
        a = day_one_answers.get(f"q{i}", "")
        lines.append(f"**Q{i}:** {q}")
        lines.append(f"**A:** {a[:400]}" + ("..." if len(a) > 400 else ""))
        lines.append("")
    return "\n".join(lines)


def generate_onboarding_brief_md(day_one_answers: dict) -> str:
    """Generate onboarding_brief.md from day_one_brief.json with evidence citations."""
    lines = [
        "# FDE Day-One Brief",
        "",
        "Auto-generated answers to the five questions every new FDE needs answered. Evidence from static analysis and data lineage (file paths and graph traversal).",
        "",
        "---",
        "",
    ]
    questions = day_one_answers.get("questions") or []
    for i in range(1, 6):
        q = questions[i - 1] if i <= len(questions) else f"Question {i}"
        a = day_one_answers.get(f"q{i}", "")
        lines.append(f"## {i}. {q}")
        lines.append("")
        lines.append(a)
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)


def write_semantic_index(module_graph: nx.DiGraph, output_dir: Path) -> Path:
    """Write semantic_index/ with module path and purpose for search. Returns path to index dir."""
    index_dir = output_dir / "semantic_index"
    index_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for n in module_graph.nodes():
        d = module_graph.nodes[n]
        purpose = _safe_get(d, "purpose_statement")
        domain = _safe_get(d, "domain_cluster")
        if purpose or domain:
            entries.append({"path": n, "purpose_statement": purpose, "domain_cluster": domain})
    index_path = index_dir / "index.json"
    with open(index_path, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2)
    return index_dir


def append_trace_entry(trace_path: Path, action: str, agent: str, details: dict) -> None:
    """Append one JSONL record to cartography_trace.jsonl."""
    trace_path.parent.mkdir(parents=True, exist_ok=True)
    record = {"action": action, "agent": agent, **details}
    with open(trace_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


class Archivist:
    """
    Living context maintainer: CODEBASE.md, onboarding_brief.md, lineage_graph.json,
    semantic_index/, cartography_trace.jsonl. Mirrors Week 1 audit pattern.
    """

    def __init__(self, output_dir: str | Path) -> None:
        self.output_dir = Path(output_dir)

    def run(
        self,
        module_graph: nx.DiGraph,
        lineage_graph: nx.DiGraph,
        survey_analytics: dict,
        day_one_answers: dict,
        repo_name: str = "codebase",
        trace_path: Path | None = None,
    ) -> dict[str, Path]:
        """
        Generate all Archivist artifacts. Optionally append to trace_path.
        Returns paths to written files.
        """
        trace_path = trace_path or self.output_dir / "cartography_trace.jsonl"
        written: dict[str, Path] = {}

        codebase_md = generate_CODEBASE_md(
            module_graph, lineage_graph, survey_analytics, day_one_answers, repo_name
        )
        codebase_path = self.output_dir / "CODEBASE.md"
        codebase_path.write_text(codebase_md, encoding="utf-8")
        written["CODEBASE.md"] = codebase_path
        append_trace_entry(trace_path, "write_artifact", "archivist", {"artifact": "CODEBASE.md", "path": str(codebase_path)})

        onboarding_md = generate_onboarding_brief_md(day_one_answers)
        onboarding_path = self.output_dir / "onboarding_brief.md"
        onboarding_path.write_text(onboarding_md, encoding="utf-8")
        written["onboarding_brief.md"] = onboarding_path
        append_trace_entry(trace_path, "write_artifact", "archivist", {"artifact": "onboarding_brief.md", "path": str(onboarding_path)})

        index_dir = write_semantic_index(module_graph, self.output_dir)
        written["semantic_index"] = index_dir
        append_trace_entry(trace_path, "write_artifact", "archivist", {"artifact": "semantic_index", "path": str(index_dir)})

        append_trace_entry(trace_path, "run_complete", "archivist", {"artifacts": list(written.keys())})
        return written
